### ISSUE TITLE
Consecutive spaces make config file invalid

### ISSUE THREAD

**Issue by GCChelp** [odedlaz/suex#25]
When more than one blank is used to separate the entries of a line in the configuration file (e.g. to make it look more neat or clearly formatted) the configuration file is invalid.
Wouldn't it be better to allow any kind of whitespace as delimiter between the components of a line?

**Comment by odedlaz** [comment]
@GCChelp , Can you provide an example of an invalid / invalid configuration please?

**Comment by GCChelp** [comment]
This nicely formatted entries are considered invalid:
permit nopass username  as root cmd /usr/bin/systemctl args status  nginx.service
permit nopass username  as root cmd /usr/bin/systemctl args restart nginx.service
permit nopass username  as root cmd /usr/bin/systemctl args stop&nbsp;  nginx.service
permit nopass username  as root cmd /usr/bin/systemctl args start&nbsp;  nginx.service

While it works if I replace redundant spaces by only one:
permit nopass username as root cmd /usr/bin/systemctl args status nginx.service
permit nopass username as root cmd /usr/bin/systemctl args restart nginx.service
permit nopass username as root cmd /usr/bin/systemctl args stop nginx.service
permit nopass username as root cmd /usr/bin/systemctl args start nginx.service

Note: The redundant spaces are after `start` and `stop`, such that the following word continues in the same column for all lines. Same applies to usernames with different length. (fixed width font)

(Could not insert the lines as 'code' because Markdown removed the consecutive spaces.)

BTW: I found out about the regular expression syntax to shorten configs like this in the meantime.   ;-)

Using version 0.2.2 downloaded as RPM package and installed on SLES12 SP2.

**Comment by odedlaz** [comment]
@GCChelp, I'm on it.

**Comment by odedlaz** [comment]
Fixed in https://github.com/odedlaz/suex/commit/199c972f4217a4adc6e40aa210d02fc33310a32c.
