### ISSUE TITLE
Conflict with identical username and group?

### ISSUE THREAD

**Issue by GCChelp** [odedlaz/suex#28]
Does it cause a conflict if the username is identical to the group?

We have a group with some developers working on a service plus a generic account under which the service is running. The generic account has the same name as the group.

Problem description:
The following group configuration entry is in  suex.conf.
`permit nopass :foo as root cmd /usr/bin/systemctl args (status|restart|stop|start) nginx.service`

It works for all members of the group, but not for the generic account  foo .
`% id`
`uid=316(foo) gid=253(foo) groups=253(foo),110(a),120(b),122(c),126(d),230(e),248(f),254(g),908(h)`
`% suex systemctl status nginx.service`
`You are not allowed to execute '/usr/bin/systemctl status nginx.service' as root`

I have to add an additional username based configuration entry for  foo  to enable it as well:
`permit nopass foo as root cmd /usr/bin/systemctl args (status|restart|stop|start) nginx.service`

Only with this additional entry foo can suex the command, too.

**Comment by odedlaz** [comment]
Fixed in https://github.com/odedlaz/suex/commit/cfe04fb50ff16cbe23f8ecbef5528f39e794089b.

Thanks for the input!
