### ISSUE TITLE
doas fails to parse doas.conf

### ISSUE THREAD

**Issue by eclipseo** [odedlaz/suex#9]
When trying to edit doas.conf, it always fails to parse the command, despite them being valid:

```
DEBUG - parsing line 1: '# Welcome to doas!'
DEBUG - line 1 is a comment, skipping.
DEBUG - parsing line 2: 'permit persist :wheel'
DEBUG - couldn't parse: permit persist :wheel
ERROR - line invalid
```

**Comment by odedlaz** [comment]
The line is not valid. a valid line consists of all these parts:
**permit**|**deny** [*options*] *identity* [**as** *target*] [**cmd** *command* [**args** ...]]
in your example, the line should be:
```bash
# for no args
permit persist <username> as <destination-username> cmd <your-cmd>
# if you want args
permit persist <username> as <destination-username> cmd <your-cmd> args <your args>
```
for example, if you want `eclipseo` to be able to run `/usr/bin/whoami` as root:
```
permit persist eclipseo as root cmd /usr/bin/whoami
```

**Comment by eclipseo** [comment]
But in the REAMDE you say:

>Ted Unagst's wrote a great blog post called doas mastery. Because suex has complete feature parity 
>with doas, the mentioned post should be a good starting point.

Thus I copied the line from the blog post expectinq it to work.

**Comment by odedlaz** [comment]
That's correct. I'll update the blog post.
I decided to force users to explicitly specify the destination user instead of defaulting to `root` when non is used. Same goes for `cmd`.
